apiVersion: v1
kind: Service
metadata:
    name: jenkins-service
    namespace: jenkins-dev
spec:
    selector:
        app: jenkins
    ports:
        -   protocol: TCP
            port: 8080
            targetPort: 8080
            nodePort: 30000
    type: NodePort
