apiVersion: v1
kind: PersistentVolume
metadata:
    name: jenkins-nfs-persistent-volume
    namespace: jenkins-dev
spec:
    capacity:
        storage: 10Gi
    accessModes:
        - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
        server: 127.0.0.1 # nfs.gintra
        path: /var/opt/setmy.info/gintra

