micronaut:
    application:
        name: micronaut-start-project
        context-path: /
    caches:
        micronaut-start-project:
            maximumSize: 20
            expire-after-access: 15s
    config-client:
        enabled: true
#    security.endpoints.login.enabled: true
#    security.endpoints.oauth.enabled: true
#    security.token.jwt.signatures.secret.generator.secret: ${JWT_GENERATOR_SIGNATURE_SECRET\:pleaseChangeThisSecretForANewOne}
#    security.endpoints.logout.enabled: true
#    security.session.loginSuccessTargetUrl: /
#    security.session.loginFailureTargetUrl: /

# Management endpoints
#endpoints:
#    all:
#        port: 8085

example:
    property:
        name: application.yml
        other: application.yml

datasources.default.url: jdbc\:h2\:mem\:devDb;MVCC\=TRUE;LOCK_TIMEOUT\=10000;DB_CLOSE_ON_EXIT\=FALSE
datasources.default.driverClassName: org.h2.Driver
datasources.default.username: sa
datasources.default.password: 
jpa.default.properties.hibernate.hbm2ddl.auto: update
datasources.default.schema-generate: CREATE_DROP
datasources.default.dialect: H2
#infinispan.client.hotrod.server.host: infinispan.example.com
#infinispan.client.hotrod.server.port: 10222
#rabbitmq.uri: amqp\://localhost\:5672
