#!/bin/sh

# Copyright Imre Tabur

DOCKER_PROJECT_NAME="setmy-info-centos-java"
DOCKER_PROJECT_VERSION="v1.11.0"
DOCKER_ID_USER="xxxxxx"
DOCKER_ID_ORGANIZATION="setmyinfo"
DOCKER_CONTENT_TRUST=1

JDK_TAR_FILE_NAME=openjdk-11+28_linux-x64_bin.tar.gz
wget -c https://download.java.net/java/GA/jdk11/28/GPL/$JDK_TAR_FILE_NAME -O $JDK_TAR_FILE_NAME
tar xvzf $JDK_TAR_FILE_NAME

docker build -t  "$DOCKER_ID_ORGANIZATION/$DOCKER_PROJECT_NAME:$DOCKER_PROJECT_VERSION" .
docker image tag "$DOCKER_ID_ORGANIZATION/$DOCKER_PROJECT_NAME:$DOCKER_PROJECT_VERSION" $DOCKER_ID_ORGANIZATION/$DOCKER_PROJECT_NAME:latest
docker images
docker login
docker image push $DOCKER_ID_ORGANIZATION/$DOCKER_PROJECT_NAME:latest
docker image push $DOCKER_ID_ORGANIZATION/$DOCKER_PROJECT_NAME:$DOCKER_PROJECT_VERSION

exit ${?}
