version: '3'
services:
    node-start-project:
        build: 
            context: ./node-start-project
            dockerfile: Dockerfile
        image: node-start-project:1.2.0-SNAPSHOT
        ports:
            - "4000:3000"
    micronaut-start-project:
        build: 
            context: ./micronaut-start-project
            dockerfile: Dockerfile
        image: micronaut-start-project:1.2.0-SNAPSHOT
        ports:
            - "8080:8080"
