version: '3'
services:
    node-start-project:
        build: 
            context: ./node-start-project
            dockerfile: Dockerfile
        image: node-start-project:1.2.0-SNAPSHOT
        ports:
            - "4000:3000"
    micronaut-start-project:
        build: 
            context: ./micronaut-start-project
            dockerfile: Dockerfile
        image: micronaut-start-project:1.2.0-SNAPSHOT
        ports:
            - "8010:8080"
    springboot-start-project:
        build: 
            context: ./springboot-start-project
            dockerfile: Dockerfile
        image: springboot-start-project:1.2.0-SNAPSHOT
        ports:
            - "8020:8080"
    tomcat-start-project:
        build: 
            context: ./tomcat-start-project
            dockerfile: Dockerfile
        image: tomcat-start-project:1.2.0-SNAPSHOT
        ports:
            - "8030:8080"
    docker-centos-nginx:
        build: 
            context: ./docker-images/docker-centos-nginx
            dockerfile: Dockerfile
        image: setmy-info-centos-nginx:1.14.2
        ports:
            - "80:80"