---
#- hosts: all
#  become: yes
#  become_method: sudo
#  become_user: root
#  remote_user: imret
#  tasks:
#    - name: Creating folders.
#      file:
#        path: /opt/xyz
#        state: directory
#        owner: root
#        group: root
#        mode: 0775
#      tags: dirs
- hosts: all
  user: imret
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: Creating folders.
      become: yes
      become_method: sudo
      become_user: root
      file:
        path: /opt/xyz
        state: directory
        owner: root
        group: root
        mode: 0775
      tags: dirs
