apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: infinispan-persistent-volume-claim
    namespace: microservice-local
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
