apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: microservice-nfs-persistent-volume-claim
    namespace: local
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 5Gi
    storageClassName: ""
    volumeName: microservice-nfs-persistent-volume
