apiVersion: v1
kind: ConfigMap
metadata:
    name: microservice-config-map
    namespace: microservice-local
    # <service-name>.<namespace>.svc.cluster.local
    # <pod-name>.<service-name>.<namespace>.svc.cluster.local
    # postgresql-1.postgres-service.microservice-local.svc.cluster.local
data:
    #spring-datasource-url: "jdbc:postgresql://postgres-service.microservice-local.svc.cluster.local:5432/microservice-db"
    spring-datasource-url: "jdbc:h2:file:./target/local;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL"
    infinispan-server-list: "infinispan-service.microservice-local.svc.cluster.local"
immutable: true
