apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: postgres-persistent-volume-claim
    namespace: microservice-local
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
#    storageClassName: ""
#    volumeName: postgres-persistent-volume
