#!/bin/sh

# Copyright 2019 Imre Tabur <imre.tabur@eesti.ee>

OPT_DIR=/opt
ZEEBE_OPT_DIR=${OPT_DIR}/zeebe-broker
ZEEBE_BIN_DIR=${ZEEBE_OPT_DIR}/bin
ZEEBE_WORKING_DIR=${ZEEBE_OPT_DIR}

#Zeebe related environment variables
export ZEEBE_LOG_LEVEL=info

cd ${ZEEBE_WORKING_DIR}
${ZEEBE_BIN_DIR}/broker

exit ${?}
