apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: argo-workflow-role-binding
    namespace: training
subjects:
    -   kind: ServiceAccount
        name: default
        namespace: training
roleRef:
    kind: ClusterRole
    name: argo-workflow-role
    apiGroup: rbac.authorization.k8s.io
