apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: argo-workflow-role
rules:
    -   apiGroups: [ "" ]
        resources: [ "pods", "pods/log", "pods/status" ]
        verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
