#!/bin/sh
# Copyright (C) 2024 Imre Tabur <imre.tabur@mail.ee>
set -e
OPT_DIR=/opt
STEALER_OPT_DIR=${OPT_DIR}/stealer
STEALER_BIN_OPT_DIR=${STEALER_OPT_DIR}/bin
STEALER_LIB_OPT_DIR=${STEALER_OPT_DIR}/lib

exec java -cp "${STEALER_LIB_OPT_DIR}/*" info.setmy.stealer.cli.Application "$@"
