# Copyright Imre Tabur

JAIL_PROJECT_NAME="setmy-info-freebsd-java"
JAIL_PROJECT_VERSION="17.0.1"

all: build

build:
	smi-jail JAIL=$(JAIL_PROJECT_NAME) TAG=$(JAIL_PROJECT_VERSION)

.PHONY: all build
