#!/bin/sh

# Copyright Imre Tabur

DOCKER_PROJECT_NAME="setmy-info-centos-java-tomcat"
DOCKER_PROJECT_VERSION="v9.0.14"
DOCKER_ID_USER="xxxxxx"
DOCKER_ID_ORGANIZATION="setmyinfo"
DOCKER_CONTENT_TRUST=1
TOMCAT_VERSION=9.0.14
TOMCAT_DIR_NAME=apache-tomcat-${TOMCAT_VERSION}
TOMCAT_TAR_FILE_NAME=$TOMCAT_DIR_NAME.tar.gz
wget -c https://www-eu.apache.org/dist/tomcat/tomcat-9/v${TOMCAT_VERSION}/bin/$TOMCAT_TAR_FILE_NAME -O $TOMCAT_TAR_FILE_NAME
tar xvzf $TOMCAT_TAR_FILE_NAME

docker build -t  "$DOCKER_ID_ORGANIZATION/$DOCKER_PROJECT_NAME:$DOCKER_PROJECT_VERSION" .
docker image tag "$DOCKER_ID_ORGANIZATION/$DOCKER_PROJECT_NAME:$DOCKER_PROJECT_VERSION" $DOCKER_ID_ORGANIZATION/$DOCKER_PROJECT_NAME:latest
docker images
docker login
docker image push $DOCKER_ID_ORGANIZATION/$DOCKER_PROJECT_NAME:latest
docker image push $DOCKER_ID_ORGANIZATION/$DOCKER_PROJECT_NAME:$DOCKER_PROJECT_VERSION

exit ${?}