server:
    port: 8080
    servlet:
        context-path: /
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json

spring:
    application:
        name: springboot-start-project
        console:
            #           TODO : by default (LIVE) false, in development and local developer true
            #            enabled: false
            enabled: true
    main:
        banner-mode: "console"
    datasource:
        url: jdbc:h2:file:./target/local;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
        #url: jdbc:hsqldb:hsql://localhost:8877
        driverClassName: org.h2.Driver
        #driverClassName: org.postgresql.Driver
        #driverClassName: org.hsqldb.jdbc.JDBCDriver
        #driverClassName: org.apache.derby.jdbc.ClientDriver
        username: sa
        password:
        hikari:
            maximum-pool-size: 10
            minimum-idle: 5
            connection-timeout: 30000
            idle-timeout: 600000
            max-lifetime: 1800000
    h2:
        console:
            enabled: true
    liquibase:
        # With profiles in dev only
        contexts: load_example_data
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                #dialect: org.hibernate.dialect.PostgreSQLDialect
                #dialect: org.hibernate.dialect.HSQLDialect
                #dialect: org.hibernate.dialect.DerbyTenSevenDialect
                #dialect: org.hibernate.dialect.Oracle10gDialect
                id:
                    new_generator_mappings: false
                # TODO : by default false (LIVE) and developers true
                #format_sql: false
                format_sql: true
    graphql:
        graphiql:
            enabled: true
    quartz:
        job-store-type: jdbc
        jdbc:
            initialize-schema: always
        properties:
            org:
                quartz:
                    scheduler:
                        instanceName: ClusteredScheduler
                        instanceId: AUTO
                    threadPool:
                        class: org.quartz.simpl.SimpleThreadPool
                        threadCount: 25
                        threadPriority: 5
                    jobStore:
                        class: org.quartz.impl.jdbcjobstore.JobStoreTX
                        driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
                        tablePrefix: QRTZ_
                        isClustered: true
                        dataSource: quartzDataSource
                    dataSource:
                        quartzDataSource:
                            driver: org.h2.Driver
                            URL: jdbc:h2:file:./target/local;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
                            user: sa
                            password:

management:
    endpoints:
        #        enabled-by-default: true
        web:
            exposure:
                include: health, info
    endpoint:
        info:
            enabled: true

springdoc:
    show-actuator: true
    api-docs:
        version: openapi_3_1
    enable-groovy: true

maven:
    project:
        groupId: @project.groupId@
        artifactId: @project.artifactId@

#liquibaseDataSource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:./target/default
#    username: sa
#    password:
