server:
  host: 0.0.0.0
  port: 5000
  templateFolder: '../templates'
  staticFolder: '../static'
rest:
  root: ''
log:
  directory: ./
  fileName: python-service-log.log
  level: DEBUG
  format: '%(asctime)-15s %(message)s'
