<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>info.setmy</groupId>
        <artifactId>multi-projects</artifactId>
        <version>1.2.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>springboot-start-project</artifactId>
    <packaging>pom</packaging>

    <name>springboot-start-project</name>
    <description>Spring Boot Master POM</description>
    <url>https://setmy-info.github.io</url>

    <modules>
        <module>springboot-start-app</module>
        <module>spring-boot-example-starter</module>
        <module>spring-boot-accounting-starter</module>
        <module>spring-boot-ai-starter</module>
        <module>spring-boot-clojure-starter</module>
        <module>spring-boot-communication-starter</module>
        <module>spring-boot-crawler-starter</module>
        <module>spring-boot-db-starter</module>
        <module>spring-boot-document-db-starter</module>
        <module>spring-boot-exec-starter</module>
        <module>spring-boot-graph-starter</module>
        <module>spring-boot-graph-db-starter</module>
        <module>spring-boot-graphics-starter</module>
        <module>spring-boot-hr-starter</module>
        <module>spring-boot-indexing-starter</module>
        <module>spring-boot-jwt-models-starter</module>
        <module>spring-boot-lexer-parser-starter</module>
        <module>spring-boot-linguistics-starter</module>
        <module>spring-boot-modular-ssn-starter</module>
        <module>spring-boot-protocol-starter</module>
        <module>spring-boot-reports-starter</module>
        <module>spring-boot-rest-client-starter</module>
        <module>spring-boot-scripting-starter</module>
        <module>spring-boot-stealer-starter</module>
        <module>spring-boot-storage-starter</module>
        <module>spring-boot-templates-starter</module>
        <module>spring-boot-vcs-starter</module>
        <module>spring-boot-web-starter</module>
        <module>spring-boot-web-doc-format-starter</module>
        <module>spring-boot-wf-starter</module>
    </modules>

</project>
