<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>info.setmy</groupId>
        <artifactId>multi-projects</artifactId>
        <version>1.2.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>springboot-start-project</artifactId>
    <packaging>pom</packaging>

    <name>springboot-start-project</name>
    <description>Spring Boot Master POM</description>
    <url>https://setmy-info.github.io</url>

    <!-- Single source of truth for all Spring Boot module properties.
         springboot-start-app and all spring-boot-*-starter modules inherit from this POM. -->
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <encoding.level>UTF-8</encoding.level>
        <!--maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target-->
        <java.version>25</java.version>
        <maven.build.timestamp.format>dd.MM.yyyy HH:mm</maven.build.timestamp.format>
        <buildTimestamp>${maven.build.timestamp}</buildTimestamp>
        <dependency.locations.enabled>false</dependency.locations.enabled>

        <junit.version>4.13.2</junit.version>
        <junit5.version>5.13.4</junit5.version>
        <junit.platform.version>1.14.2</junit.platform.version>
        <mockito.version>5.22.0</mockito.version>
        <assertj.version>3.27.3</assertj.version>
        <archunit.version>1.4.1</archunit.version>
        <jacoco.version>0.8.14</jacoco.version>
        <failsafe.version>3.5.5</failsafe.version>
        <surefire.version>3.5.5</surefire.version>
        <!--log4j.verion>1.2.17</log4j.verion -->
        <log4j2.verion>2.25.3</log4j2.verion>
        <logback.verion>1.5.32</logback.verion>
        <slf4j.version>2.0.17</slf4j.version>
        <lucene.version>10.4.0</lucene.version>
        <groovy.version>5.0.4</groovy.version>
        <cucumber.version>7.34.3</cucumber.version>
        <pitest.version>1.22.1</pitest.version>
        <jersey.version>3.1.11</jersey.version>
        <jackson.version>2.19.2</jackson.version>
        <dockerfile.maven.version>1.4.13</dockerfile.maven.version>
        <dependency.check.version>10.0.3</dependency.check.version>
        <maven.version>3.9.11</maven.version>
        <maven.clean.plugin.version>3.5.0</maven.clean.plugin.version>
        <maven.resources.plugin.version>3.3.1</maven.resources.plugin.version>
        <maven.compiler.plugin.version>3.14.1</maven.compiler.plugin.version>
        <maven.site.plugin.version>3.21.0</maven.site.plugin.version>
        <maven.release.plugin.version>3.3.1</maven.release.plugin.version>
        <maven.source.plugin.version>3.3.1</maven.source.plugin.version>
        <maven.javadoc.plugin.version>3.12.0</maven.javadoc.plugin.version>
        <maven.gpg.plugin.version>3.2.8</maven.gpg.plugin.version>
        <maven.project.info.reports.plugin.version>3.9.0</maven.project.info.reports.plugin.version>
        <maven.checkstyle.plugin.version>3.6.0</maven.checkstyle.plugin.version>
        <maven.changes.plugin.version>2.12.1</maven.changes.plugin.version>
        <maven.assembly.plugin>3.8.0</maven.assembly.plugin>
        <maven.plugin.annotations.version>3.15.2</maven.plugin.annotations.version>
        <maven.versions.maven.plugin>2.21.0</maven.versions.maven.plugin>
        <gmavenplus.plugin.version>4.3.1</gmavenplus.plugin.version>
        <buildnumber.maven.plugin.version>3.3.0</buildnumber.maven.plugin.version>
        <nexus.staging.plugin.version>1.7.0</nexus.staging.plugin.version>
        <spring.boot.verion>4.0.3</spring.boot.verion>
        <taglist.maven.plugin.version>3.2.2</taglist.maven.plugin.version>
        <servlet.api.version>4.0.1</servlet.api.version>
        <jaxb.api.version>2.3.1</jaxb.api.version>
        <hibernate.version>7.2.0.Final</hibernate.version>
        <hibernate.validator.version>9.1.0.Final</hibernate.validator.version>
        <hibernate.ehcache.version>5.6.15.Final</hibernate.ehcache.version>
        <ehcache.version>3.11.1</ehcache.version>
        <commons.dbcp.version>2.14.0</commons.dbcp.version>
        <commons.io.version>2.21.0</commons.io.version>
        <commons.codec.version>1.21.0</commons.codec.version>
        <commons.lang3.version>3.20.0</commons.lang3.version>
        <snakeyaml.version>2.5</snakeyaml.version>
        <javax.validation.api.version>2.0.1.Final</javax.validation.api.version>
        <javax.inject.version>1</javax.inject.version>
        <javax.cache.api.version>1.1.1</javax.cache.api.version>
        <java.jwt.version>4.5.1</java.jwt.version><!--java.jwt.version>4.0.0</java.jwt.version-->
        <rest.assured.version>5.5.7</rest.assured.version>
        <liquibase.version>5.0.1</liquibase.version>
        <infinispan.version>16.1.0</infinispan.version>
        <quartz.verion>2.5.2</quartz.verion>
        <lombok.version>1.18.42</lombok.version>
        <mapstruct.version>1.6.3</mapstruct.version>
        <swagger.version>3.1.0</swagger.version>
        <swagger.annotations.version>1.6.3</swagger.annotations.version>
        <swagger.models.version>1.6.3</swagger.models.version>
        <springdoc.version>1.8.0</springdoc.version>
        <jakarta.xml.bind.api.version>4.0.5</jakarta.xml.bind.api.version>
        <jakarta.validation.api.version>3.1.0</jakarta.validation.api.version>
        <jakarta.inject.api.version>2.0.1</jakarta.inject.api.version>
        <picocli.version>4.7.7</picocli.version>
        <find.bugs.version>3.0.5</find.bugs.version>
        <spot.bugs.version>4.9.8.2</spot.bugs.version>
        <clojure.version>1.12.4</clojure.version>
        <tensorflow.core.version>1.1.0</tensorflow.core.version>
        <tensorflow.ndarray.version>1.0.0</tensorflow.ndarray.version>
        <tensorflow.framework.version>1.1.0</tensorflow.framework.version>
        <jsoup.version>1.22.1</jsoup.version>
        <selenium.version>4.41.0</selenium.version>
        <feign.version>13.9.3</feign.version>
        <jasperreports.version>7.0.3</jasperreports.version>
        <itextpdf.version>5.5.13.4</itextpdf.version>
        <tika.version>3.2.3</tika.version>
        <kotlin.version>2.3.10</kotlin.version>
        <camel.version>4.18.0</camel.version>
        <hikari.version>7.0.2</hikari.version>
        <nvdApiKey>${nvdApiKey}</nvdApiKey>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring.boot.verion}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <modules>
        <module>springboot-start-app</module>
        <module>spring-boot-example-starter</module>
        <module>spring-boot-accounting-starter</module>
        <module>spring-boot-ai-starter</module>
        <module>spring-boot-clojure-starter</module>
        <module>spring-boot-communication-starter</module>
        <module>spring-boot-crawler-starter</module>
        <module>spring-boot-db-starter</module>
        <module>spring-boot-document-db-starter</module>
        <module>spring-boot-exec-starter</module>
        <module>spring-boot-graph-starter</module>
        <module>spring-boot-graph-db-starter</module>
        <module>spring-boot-graphics-starter</module>
        <module>spring-boot-hr-starter</module>
        <module>spring-boot-indexing-starter</module>
        <module>spring-boot-jwt-models-starter</module>
        <module>spring-boot-lexer-parser-starter</module>
        <module>spring-boot-linguistics-starter</module>
        <module>spring-boot-modular-ssn-starter</module>
        <module>spring-boot-protocol-starter</module>
        <module>spring-boot-reports-starter</module>
        <module>spring-boot-rest-client-starter</module>
        <module>spring-boot-scripting-starter</module>
        <module>spring-boot-stealer-starter</module>
        <module>spring-boot-storage-starter</module>
        <module>spring-boot-templates-starter</module>
        <module>spring-boot-vcs-starter</module>
        <module>spring-boot-web-starter</module>
        <module>spring-boot-web-doc-format-starter</module>
        <module>spring-boot-wf-starter</module>
    </modules>

</project>
