PROJECT_NAME=springboot-start-project
PROJECT_VERSION=1.2.0-SNAPSHOT
PROVIDER_NAME=has

OPT_DIR=/opt
VAR_DIR=/var
PROJECT_OPT_DIR=${OPT_DIR}/${PROVIDER_NAME}
PROJECT_VAR_DIR=${VAR_DIR}/${OPT_DIR}/${PROVIDER_NAME}
PROJECT_BIN_DIR=${PROJECT_OPT_DIR}/bin
PROJECT_LIB_DIR=${PROJECT_OPT_DIR}/lib
