apiVersion: v1
kind: Service
metadata:
    name: microservice-service
    namespace: microservice-local
spec:
    selector:
        app.kubernetes.io/name: microservice
    ports:
        -   protocol: TCP
            port: 80
            targetPort: micros-port

