call tsc @ts.compile.txt @ts.files.txt
call lessc --clean-css src/main/webapp/app/css/all.less src/main/webapp/app/css/all.min.css
call uglifyjs ^
        src/main/webapp/app/js/extend.js ^
        src/main/webapp/app/js/typescript.js ^
        src/main/webapp/app/lib/html5-boilerplate/dist/js/vendor/modernizr-2.8.3.min.js ^
        src/main/webapp/app/lib/angular/angular.min.js ^
        src/main/webapp/app/lib/angular-route/angular-route.min.js ^
        src/main/webapp/app/lib/angular-cookies/angular-cookies.min.js ^
        src/main/webapp/app/lib/angular-loader/angular-loader.min.js ^
        src/main/webapp/app/lib/angular-resource/angular-resource.min.js ^
        src/main/webapp/app/lib/angular-messages/angular-messages.min.js ^
        src/main/webapp/app/lib/angular-sanitize/angular-sanitize.min.js ^
        src/main/webapp/app/js/angularLocaleChanger.js ^
        src/main/webapp/app/lib/angular-classy/angular-classy.min.js ^
        src/main/webapp/app/lib/angular-aop/build/angular-aop.min.js ^
        src/main/webapp/app/lib/angular-bootstrap/ui-bootstrap-tpls.min.js ^
        src/main/webapp/app/js/classyModelPlugin.js ^
        src/main/webapp/app/js/application.js ^
        src/main/webapp/app/components/aop/aspects.js ^
        src/main/webapp/app/components/views/view1/view1Controller.js ^
        src/main/webapp/app/components/views/view2/view2Controller.js ^
        src/main/webapp/app/components/views/login/loginController.js ^
        src/main/webapp/app/components/views/logout/logOutController.js ^
        src/main/webapp/app/components/views/dialog/modalDialogController.js ^
        src/main/webapp/app/components/views/logout/logOutDialogController.js ^
        src/main/webapp/app/components/values/values.js ^
        src/main/webapp/app/components/directives/applicationVersionDirective.js ^
        src/main/webapp/app/components/directives/languageSelectorDirective.js ^
        src/main/webapp/app/components/directives/sessionUserDirective.js ^
        src/main/webapp/app/components/resources/resources.js ^
        src/main/webapp/app/components/filters/interpolateFilter.js ^
        src/main/webapp/app/components/filters/placeholdersFilter.js ^
        src/main/webapp/app/components/services/modelService.js ^
        src/main/webapp/app/components/services/translationsService.js ^
        src/main/webapp/app/components/services/configurationService.js ^
        src/main/webapp/app/components/services/localStorageService.js ^
        src/main/webapp/app/components/services/sessionStorageService.js ^
        src/main/webapp/app/components/services/authenticationService.js ^
        src/main/webapp/app/components/services/modalDialogService.js ^
        src/main/webapp/app/components/services/sessionService.js ^
        src/main/webapp/app/components/services/httpInterceptorService.js ^
        src/main/webapp/app/components/services/timersService.js ^
        src/main/webapp/app/components/services/cookiesService.js ^
        src/main/webapp/app/components/services/schedulerService.js ^
        src/main/webapp/app/components/services/authorizationService.js ^
        src/main/webapp/app/components/services/initService.js ^
        src/main/webapp/app/lib/angular-dynamic-locale/dist/tmhDynamicLocale.js ^
        -o src/main/webapp/app/js/all.min.js
