apiVersion: v1
kind: PersistentVolume
metadata:
    name: training-persistent-volume
spec:
    capacity:
        storage: 10Gi
    accessModes:
        - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    storageClassName: standard
    hostPath:
        path: "/data/training"
