apiVersion: v1
kind: PersistentVolume
metadata:
    name: training-persistent-volume
    namespace: training
spec:
    capacity:
        storage: 10Gi
    accessModes:
        - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    storageClassName: standard
    hostPath:
        path: C:\\pub\\setmy.info\\lib\\data
