apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: training-persistent-volume-claim
    namespace: training
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 1Gi
    storageClassName: standard
    volumeName: training-persistent-volume
