.TH example "1" "Februar 2019" "Example Man 1.0.0" "Example Man Command"
.SH NAME
example \- this is short description
.SH SYNOPSIS
.B example
[\fIxxxx\fR]... [\fIyyyyy\fR]...
.SH DESCRIPTION
.\" Add any additional description here
.PP
More description. More and more and more.
Command does something \fB\-part xxx\fR nor \fB\-\-part yyyy\fR.
.PP
Some.
.PP
Additional.
.TP
\fB\-one\fR, \fB\-\-one\fR
do not ignore entries starting with .
.TP
\fB\-two\fR, \fB\-\-two\-two\fR
do not list implied . and ..
.SH OPTIONS
Options.
.SH EXAMPLES
Examples.
.SH OTHER
Other.
.SH AUTHOR
Command written by Imre Tabur.
Documentation writen by Imre Tabur.
.SH "REPORTING BUGS"
Report example bugs to bug\ imre.tabur@eesti.ee
.SH "SEE ALSO"
See also
.B another.command.
Manual is maintained as a Texinfo manual.
.B some another tools \(aqxxx.command invocation\(aq
.PP
should give you access to the complete manual.
