#!/bin/sh

# Copyright 2019 Imre Tabur <imre.tabur@eesti.ee>

OPT_DIR=/opt
INFINISPAN_OPT_DIR=${OPT_DIR}/infinispan-server
INFINISPAN_BIN_DIR=${INFINISPAN_OPT_DIR}/bin
INFINISPAN_WORKING_DIR=${INFINISPAN_OPT_DIR}

cd ${INFINISPAN_WORKING_DIR}
${INFINISPAN_BIN_DIR}/server.sh -Dinfinispan.bind.address=0.0.0.0

exit ${?}
