# Copyright Imre Tabur

JAIL_PROJECT_NAME="setmy-info-freebsd-nginx"
JAIL_PROJECT_VERSION="1.20.2"

all: build

build:
	smi-jail JAIL=$(JAIL_PROJECT_NAME) TAG=$(JAIL_PROJECT_VERSION)

.PHONY: all build
