server:
    port: 8080
    context-path: /rest
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json

spring: 
    main:
        banner-mode: "off"
    application:
        name: springboot-start-project
        console:
            enabled: false
    security:
        user:
            name: ${SPRING_USER_NAME}
            password: ${SPRING_USER_PASSWORD}

dataSource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./live 
    username: sa
    password:

liquibase:
    change-log: classpath:liquibase/master.xml

scheduler:
    timeInMillis: 60000

system:
    example:
        foo: Foo text
        bar: Bar text
    cache:
        cacheName: apiCache
        cacheTimeoutMillis: 15000
    features:
        foo: false

infinispan:
    embedded:
        enabled: true
    remote:
        enabled: false

maven:
    project:
        groupId: ${project.groupId}
        artifactId: ${project.artifactId}
