server:
    port: 8080
    context-path: /rest
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json

spring: 
    main:
        banner-mode: "off"
    application:
        name: springboot-start-project
        console:
            enabled: false
    security:
        user:
            name: admin
            password: g6p8

dataSource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./live 
    username: sa
    password:

liquibase:
    change-log: classpath:liquibase/master.xml

scheduler:
    timeInMillis: 60000

system:
    example:
        foo: Foo text
        bar: Bar text
    cache:
        infinispanCacheName: cache
    features:
        foo: false
