server:
    port: 8080
    context-path: /rest
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json

spring:
    main:
        banner-mode: "off"
    application:
        name: springboot-start-project
        console:
            enabled: false
    security:
        user:
            name: ${SPRING_USER_NAME}
            password: ${SPRING_USER_PASSWORD}
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                #dialect: org.hibernate.dialect.PostgreSQLDialect
                #dialect: org.hibernate.dialect.HSQLDialect
                #dialect: org.hibernate.dialect.DerbyTenSevenDialect
                #dialect: org.hibernate.dialect.Oracle10gDialect
                id.new_generator_mappings: false
                format_sql: true

dataSource:
    driver-class-name: org.h2.Driver
    #driver-class-name: org.postgresql.Driver
    #driver-class-name: org.hsqldb.jdbc.JDBCDriver
    #driver-class-name: org.apache.derby.jdbc.ClientDriver
    #driver-class-name:
    url: jdbc:h2:file:./live
    #url: jdbc:hsqldb:hsql://localhost:8877
    username: sa
    password:

liquibase:
    change-log: classpath:liquibase/master.xml

scheduler:
    timeInMillis: 60000
    transactionTimeInMillis: 60000

system:
    example:
        foo: Foo text
        bar: Bar text
    cache:
        cacheName: apiCache
        cacheTimeoutMillis: 15000
    features:
        foo: false
    rest:
        datesUTC: true

infinispan:
    embedded:
        enabled: true
    remote:
        enabled: false

maven:
    project:
        groupId: @project.groupId@
        artifactId: @project.artifactId@

swagger:
    deepLinking: true
    defaultModelExpandDepth: 1
    defaultModelsExpandDepth: 1
    description: Sample Swagger.
    displayOperationId: false
    displayRequestDuration: false
    enableUrlTemplating: false
    enabled: true
    filter: false
    maxDisplayedTags: 0
    showExtensions: false
    title: springboot-start-project API
    useDefaultResponseMessages: false
