# Copyright Imre Tabur

JAIL_PROJECT_NAME="setmy-info-freebsd-tomcat"
JAIL_PROJECT_VERSION="10.0.12"

all: build

build:
	smi-jail JAIL=$(JAIL_PROJECT_NAME) TAG=$(JAIL_PROJECT_VERSION)

.PHONY: all build
