#!/bin/sh

# Copyright Imre Tabur

DOCKER_PROJECT_NAME="setmy-info-centos"
DOCKER_PROJECT_VERSION="v1.0.1"
DOCKER_ID_USER="xxxxxx"
DOCKER_ID_ORGANIZATION="setmyinfo"
DOCKER_CONTENT_TRUST=1

docker build -t  "$DOCKER_ID_ORGANIZATION/$DOCKER_PROJECT_NAME:$DOCKER_PROJECT_VERSION" .
docker image tag "$DOCKER_ID_ORGANIZATION/$DOCKER_PROJECT_NAME:$DOCKER_PROJECT_VERSION" $DOCKER_ID_ORGANIZATION/$DOCKER_PROJECT_NAME:latest
docker images
docker login
docker image push $DOCKER_ID_ORGANIZATION/$DOCKER_PROJECT_NAME:latest
docker image push $DOCKER_ID_ORGANIZATION/$DOCKER_PROJECT_NAME:$DOCKER_PROJECT_VERSION

exit ${?}
